type_specifier ::= "Int"
                 | "Float"
                 | "String"
                 | "Bool"
                 | "List" "<" type_specifier ">"
                 | "Ref" "<" type_specifier ">"