<statements> ::= <statement>
               | <statements> ";" <statement>
               | <statements> ";"
<block> ::= "{" <statements> "}"

<statement> ::= <assignment_statement>
              | <update_statement>
              | <if_statement>
              | <else_statement>
              | <while_statement>
              | <each_statement>
              | <variable_declaration>
              | <function_declaration>
              | <return_statement>
              | <expression_statement>

<assignment_statement> ::= <identifier> "=" <expression>
                         | <identifier> "+=" <expression>
                         | <identifier> "-=" <expression>
                         | <identifier> "*=" <expression>
                         | <identifier> "/=" <expression>
                         | <identifier> "%=" <expression>
                    
<update_statement> ::= <identifier> "++"
                     | <identifier> "--"

<if_statement> ::= "if" <expression> <block>
                 | <if_statement> "elif" <expression> <block>
<else_statement> ::= <if_statement> "else" <block>

<while_statement> ::= "while" <expression> <block>
<each_statement> ::= "each" <identifier> ":" <expression> <block>
<variable_declaration> ::= "var" <identifier> "=" <expression>
<variable_declaration> ::= "var" <identifier> ":" <type_specifier> "=" <expression>

<parameter> ::= <identifier> ":" <type_specifier>
<parameters> ::= <parameter>
               | <parameters> "," <parameter>

<function_declaration> ::= "fun" <identifier> "(" <parameters> ")" <block>
                         | "fun" <identifier> "(" <parameters> ")" ":" <type_specifier> <block>

<return_statement> ::= "return" <expression>

<expression_statement> ::= <expression>
<expression> ::= <binary_expression>
               | <unary_expression>
               | <identifier>
               | <function_call>
               | <index_expression>
               | <parenthesized_expression>
               | <literal>

<binary_expression> ::= <expression> "+" <expression>
                      | <expression> "-" <expression>
                      | <expression> "/" <expression>
                      | <expression> "*" <expression>
                      | <expression> "&&" <expression>
                      | <expression> "||" <expression>
                      | <expression> "<" <expression>
                      | <expression> ">" <expression>
                      | <expression> "<=" <expression>
                      | <expression> ">=" <expression>
                      | <expression> "==" <expression>
                      | <expression> "!=" <expression>

<unary_expression> ::= "-" <expression>
                     | "!" <expression>


<expressions> ::= <expressions> "," <expression>
                | <expression>
<function_call> ::= <identifier> "(" <arguments> ")"

<parenthesized_expression> ::= "(" <expression> ")"

<literal> ::= <int> | <float> | <string> | <boolean> | <list> | <null>
<string> ::= string_token
<int> ::= int_token
<float> ::= float_token
<boolean> ::= "true" | "false"
<null> ::= "null"

<list> ::= "[" <expressions> "]"

<type_specifier> ::= "Int"
               | "Float"
               | "String"
               | "Bool"
               | <generic_type>
<generic_type> ::= <type_specifier> "<" <type_specifier> ">"

<identifier> ::= identifier_token


# Extra om jag har tid över

<statement> ::= <throw_statement>
              | <try_statement>
              | <namespace_declaration>

<throw_statement> ::= "throw" <expression>
<try_statement> ::= "try" <block> "catch" "(" <identifier> ")" <block>
                  | "try" <block> "catch" <block>

<namespace_declaration> ::= "namespace" <identifier> <block>
<identifier> ::= identifier_token
               | <identifier> "." <identifier>
