##############
# Statements #
##############

program ::= statements

statements ::= statement
             | statements statement

block ::= "{" statements "}"

statement ::= if_statement
            | else_statement
            | while_statement
            | each_statement
            | variable_declaration_statement
            | function_declaration_statement
            | return_statement
            | continue_statement
            | break_statement
            | throw_statement
            | try_statement
            | expression_statement

if_statement ::= "if" expression block
               | if_statement "elif" expression block
else_statement ::= if_statement "else" block

while_statement ::= "while" expression block

each_statement ::= "each" identifier ":" expression block

variable_declaration_statement ::= "var" identifier "=" expression
                                 | "var" identifier ":" type_specifier "=" expression

parameter ::= identifier ":" type_specifier
parameters ::= parameter
             | parameters "," parameter
function_declaration_statement ::= "fun" identifier "(" parameters ")" block
                                 | "fun" identifier "(" parameters ")" ":" type_specifier block

return_statement ::= "return" expression

continue_statement ::= "continue"

break_statement ::= "break"

throw_statement ::= "throw" expression

try_statement ::= "try" block "catch" identifier block
                | "try" block "catch" block

expression_statement ::= expression ";"

###############
# Expressions #
###############

comma_separated_expressions ::= expression
                              | comma_separated_expressions "," expression

expression ::= assignment_expression

assignment_operator := "=" | "+=" | "-=" | "*=" | "/=" | "%=" | "&=" | "|="
assignment_expression ::= update_expression ( assignment_operator update_expression )*

update_operator ::= "++" | "--"
update_expression ::= expression ( update_operator )*

logical_or_expression ::= logical_and_expression ( "||" logical_and_expression )*

logical_and_expression ::= equality_expression ( "&&" equality_expression )*

equality_operator ::= "==" | "!="
equality_expression ::= comparison_expression ( equality_operator comparison_expression )*

comparison_operator ::= "<" | "<=" | ">" | ">="
comparison_expression ::= additive_expression ( comparison_operator additive_expression )*

additive_operator ::= "+" | "-"
additive_operator ::= multiplicative_expression ( additive_operator multiplicative_expression )*

multiplicative_operator ::= "*" | "/" | "%"
multiplicative_expression ::= unary_expression ( multiplicative_operator unary_expression )*

unary_operator ::= "!" | "-" | "*" | "&"
unary_expression ::= unary_operator index_expression
                   | index_expression

index_expression ::= call_expression ( "[" expression "]" )*

call_expression ::= primary_expression ( "(" comma_separated_expressions ")" )*

primary_expression ::= "true"
                     | "false"
                     | "null"
                     | "[" comma_separated_expressions "]"
                     | "(" expression ")"
                     | INT
                     | FLOAT
                     | STRING
                     | IDENTIFIER

###################
# Type specifiers #
###################

type_specifier ::= "Int"
                 | "Float"
                 | "String"
                 | "Bool"
                 | "List" "<" type_specifier ">"
                 | "Ref" "<" type_specifier ">"
